
    alter table Doctor 
        drop constraint FK5B4D8B0EF1373157a547d3f

    alter table Doctor_HorariosDeAtencion 
        drop constraint FKC68909538DD8E881

    alter table Doctor_HorariosDeAtencion 
        drop constraint FKC6890953C6D94FDF

    alter table Doctor_Hospital 
        drop constraint FKD5A18D5AA46CABD1

    alter table Doctor_Hospital 
        drop constraint FKD5A18D5AC6D94FDF

    alter table Doctor_ObraSocial 
        drop constraint FK72CD446F83108642

    alter table Doctor_ObraSocial 
        drop constraint FK72CD446FC6D94FDF

    alter table Doctor_Turno 
        drop constraint FK81DE5472D5B9F366

    alter table Doctor_Turno 
        drop constraint FK81DE5472C6D94FDF

    alter table Especificacion_Doctor 
        drop constraint FK18ACECEF4589B8DF

    alter table Especificacion_Doctor 
        drop constraint FK18ACECEFC5FD4031

    alter table HistoriaClinica_Consulta 
        drop constraint FKECF4C1B85B001AE5

    alter table HistoriaClinica_Consulta 
        drop constraint FKECF4C1B8AF60E735

    alter table Hospital 
        drop constraint FKF1C1625AF137315

    alter table Hospital_Doctor 
        drop constraint FK973A9EC4EED2E8BF

    alter table Hospital_Doctor 
        drop constraint FK973A9EC4C5FD4031

    alter table ObraSocial_Doctor 
        drop constraint FK64C4F60F6984B77F

    alter table ObraSocial_Doctor 
        drop constraint FK64C4F60FC5FD4031

    alter table Paciente 
        drop constraint FK5B4D8B0EF13731530817791

    alter table Paciente 
        drop constraint FK308177916984B77F

    alter table Paciente_HistoriaClinica 
        drop constraint FKFDD848E8077C95F

    alter table Paciente_HistoriaClinica 
        drop constraint FKFDD848EF6C60F61

    alter table Paciente_Turno 
        drop constraint FKAEA6C944D5B9F366

    alter table Paciente_Turno 
        drop constraint FKAEA6C9448077C95F

    alter table Usuario 
        drop constraint FK5B4D8B0EF137315

    drop table Consulta if exists

    drop table Direccion if exists

    drop table Doctor if exists

    drop table Doctor_HorariosDeAtencion if exists

    drop table Doctor_Hospital if exists

    drop table Doctor_ObraSocial if exists

    drop table Doctor_Turno if exists

    drop table Especificacion if exists

    drop table Especificacion_Doctor if exists

    drop table HistoriaClinica if exists

    drop table HistoriaClinica_Consulta if exists

    drop table HorariosDeAtencion if exists

    drop table Hospital if exists

    drop table Hospital_Doctor if exists

    drop table ObraSocial if exists

    drop table ObraSocial_Doctor if exists

    drop table Paciente if exists

    drop table Paciente_HistoriaClinica if exists

    drop table Paciente_Turno if exists

    drop table Turno if exists

    drop table Usuario if exists

    drop sequence hibernate_sequence

    create table Consulta (
        id integer generated by default as identity (start with 1),
        date timestamp,
        texto varchar(255),
        primary key (id)
    )

    create table Direccion (
        id bigint generated by default as identity (start with 1),
        altura integer,
        calle varchar(255),
        ciudad varchar(255),
        departamento varchar(255),
        pais varchar(255),
        piso varchar(255),
        provincia varchar(255),
        primary key (id)
    )

    create table Doctor (
        id bigint not null,
        DNI varchar(255),
        admin boolean,
        apellido varchar(255),
        doctor boolean,
        email varchar(255),
        fechaDeNacimiento varchar(255),
        nombre varchar(255),
        password varchar(255),
        direccion_id bigint,
        primary key (id),
        unique (DNI),
        unique (email)
    )

    create table Doctor_HorariosDeAtencion (
        Doctor_id bigint not null,
        horarios_id bigint not null,
        unique (horarios_id)
    )

    create table Doctor_Hospital (
        Doctor_id bigint not null,
        hospitales_id integer not null
    )

    create table Doctor_ObraSocial (
        Doctor_id bigint not null,
        obrasSociales_id bigint not null
    )

    create table Doctor_Turno (
        Doctor_id bigint not null,
        turnos_id bigint not null,
        unique (turnos_id)
    )

    create table Especificacion (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table Especificacion_Doctor (
        Especificacion_id bigint not null,
        doctores_id bigint not null,
        unique (doctores_id)
    )

    create table HistoriaClinica (
        id bigint generated by default as identity (start with 1),
        especializacion varchar(255),
        nombrePaciente varchar(255),
        primary key (id)
    )

    create table HistoriaClinica_Consulta (
        HistoriaClinica_id bigint not null,
        historial_id integer not null,
        unique (historial_id)
    )

    create table HorariosDeAtencion (
        id bigint generated by default as identity (start with 1),
        duracion varchar(255),
        horarioDeFin varchar(255) not null,
        horarioDeInicio varchar(255) not null,
        primary key (id)
    )

    create table Hospital (
        id integer generated by default as identity (start with 1),
        nombre varchar(255),
        direccion_id bigint,
        primary key (id)
    )

    create table Hospital_Doctor (
        Hospital_id integer not null,
        doctores_id bigint not null
    )

    create table ObraSocial (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table ObraSocial_Doctor (
        ObraSocial_id bigint not null,
        doctores_id bigint not null
    )

    create table Paciente (
        id bigint not null,
        DNI varchar(255),
        admin boolean,
        apellido varchar(255),
        doctor boolean,
        email varchar(255),
        fechaDeNacimiento varchar(255),
        nombre varchar(255),
        password varchar(255),
        direccion_id bigint,
        ranking double,
        obraSocial_id bigint,
        primary key (id),
        unique (DNI),
        unique (email)
    )

    create table Paciente_HistoriaClinica (
        Paciente_id bigint not null,
        historiasClinicas_id bigint not null,
        unique (historiasClinicas_id)
    )

    create table Paciente_Turno (
        Paciente_id bigint not null,
        turnos_id bigint not null,
        unique (turnos_id)
    )

    create table Turno (
        id bigint generated by default as identity (start with 1),
        date timestamp,
        dateString varchar(255),
        especializacion varchar(255),
        nombreDoctor varchar(255),
        nombrePaciente varchar(255),
        primary key (id)
    )

    create table Usuario (
        id bigint not null,
        DNI varchar(255),
        admin boolean,
        apellido varchar(255),
        doctor boolean,
        email varchar(255),
        fechaDeNacimiento varchar(255),
        nombre varchar(255),
        password varchar(255),
        direccion_id bigint,
        primary key (id),
        unique (email),
        unique (DNI)
    )

    alter table Doctor 
        add constraint FK5B4D8B0EF1373157a547d3f 
        foreign key (direccion_id) 
        references Direccion

    alter table Doctor_HorariosDeAtencion 
        add constraint FKC68909538DD8E881 
        foreign key (horarios_id) 
        references HorariosDeAtencion

    alter table Doctor_HorariosDeAtencion 
        add constraint FKC6890953C6D94FDF 
        foreign key (Doctor_id) 
        references Doctor

    alter table Doctor_Hospital 
        add constraint FKD5A18D5AA46CABD1 
        foreign key (hospitales_id) 
        references Hospital

    alter table Doctor_Hospital 
        add constraint FKD5A18D5AC6D94FDF 
        foreign key (Doctor_id) 
        references Doctor

    alter table Doctor_ObraSocial 
        add constraint FK72CD446F83108642 
        foreign key (obrasSociales_id) 
        references ObraSocial

    alter table Doctor_ObraSocial 
        add constraint FK72CD446FC6D94FDF 
        foreign key (Doctor_id) 
        references Doctor

    alter table Doctor_Turno 
        add constraint FK81DE5472D5B9F366 
        foreign key (turnos_id) 
        references Turno

    alter table Doctor_Turno 
        add constraint FK81DE5472C6D94FDF 
        foreign key (Doctor_id) 
        references Doctor

    alter table Especificacion_Doctor 
        add constraint FK18ACECEF4589B8DF 
        foreign key (Especificacion_id) 
        references Especificacion

    alter table Especificacion_Doctor 
        add constraint FK18ACECEFC5FD4031 
        foreign key (doctores_id) 
        references Doctor

    alter table HistoriaClinica_Consulta 
        add constraint FKECF4C1B85B001AE5 
        foreign key (historial_id) 
        references Consulta

    alter table HistoriaClinica_Consulta 
        add constraint FKECF4C1B8AF60E735 
        foreign key (HistoriaClinica_id) 
        references HistoriaClinica

    alter table Hospital 
        add constraint FKF1C1625AF137315 
        foreign key (direccion_id) 
        references Direccion

    alter table Hospital_Doctor 
        add constraint FK973A9EC4EED2E8BF 
        foreign key (Hospital_id) 
        references Hospital

    alter table Hospital_Doctor 
        add constraint FK973A9EC4C5FD4031 
        foreign key (doctores_id) 
        references Doctor

    alter table ObraSocial_Doctor 
        add constraint FK64C4F60F6984B77F 
        foreign key (ObraSocial_id) 
        references ObraSocial

    alter table ObraSocial_Doctor 
        add constraint FK64C4F60FC5FD4031 
        foreign key (doctores_id) 
        references Doctor

    alter table Paciente 
        add constraint FK5B4D8B0EF13731530817791 
        foreign key (direccion_id) 
        references Direccion

    alter table Paciente 
        add constraint FK308177916984B77F 
        foreign key (obraSocial_id) 
        references ObraSocial

    alter table Paciente_HistoriaClinica 
        add constraint FKFDD848E8077C95F 
        foreign key (Paciente_id) 
        references Paciente

    alter table Paciente_HistoriaClinica 
        add constraint FKFDD848EF6C60F61 
        foreign key (historiasClinicas_id) 
        references HistoriaClinica

    alter table Paciente_Turno 
        add constraint FKAEA6C944D5B9F366 
        foreign key (turnos_id) 
        references Turno

    alter table Paciente_Turno 
        add constraint FKAEA6C9448077C95F 
        foreign key (Paciente_id) 
        references Paciente

    alter table Usuario 
        add constraint FK5B4D8B0EF137315 
        foreign key (direccion_id) 
        references Direccion

    create sequence hibernate_sequence
